export const metadata = {
  title: "Guide — Filament",
  description: "How to use Filament — swap tokens and provide liquidity on the LightChain AI network.",
};

export default function GuidePage() {
  return (
    <div className="container max-w-2xl mx-auto py-12 px-4">
      <h1 className="text-3xl font-bold text-[var(--clr-heading)] ae-display mb-2">
        How to use <span className="theme-gradient">Filament</span>
      </h1>
      <p className="text-[var(--clr-body)] mb-10">Filament is a non-custodial AMM on the LightChain AI network. Your wallet signs every transaction — Filament never holds your funds.</p>

      <section className="mb-10">
        <h2 className="text-lg font-bold text-[var(--clr-heading)] mb-3 border-b border-[var(--clr-border)] pb-2">Before you start</h2>
        <p className="text-sm text-[var(--clr-body)] mb-3">You need a wallet connected to LCAI mainnet and some native LCAI for gas.</p>
        <div className="rounded-xl bg-[var(--ae-haze)] border border-[var(--clr-border)] p-4 text-sm font-mono text-[var(--clr-body)] space-y-1">
          <div><span className="text-[var(--ae-aurum)]">Network</span> — LightChain AI</div>
          <div><span className="text-[var(--ae-aurum)]">Chain ID</span> — 9200</div>
          <div><span className="text-[var(--ae-aurum)]">RPC</span> — https://rpc.mainnet.lightchain.ai</div>
          <div><span className="text-[var(--ae-aurum)]">Symbol</span> — LCAI</div>
          <div><span className="text-[var(--ae-aurum)]">Explorer</span> — https://mainnet.lightscan.app</div>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-bold text-[var(--clr-heading)] mb-3 border-b border-[var(--clr-border)] pb-2">Swapping tokens</h2>
        <ol className="space-y-2 text-sm text-[var(--clr-body)] list-decimal list-inside">
          <li>Connect your wallet and make sure it is set to LCAI mainnet.</li>
          <li>Select the token you want to pay with in <strong className="text-[var(--clr-heading)]">You Pay</strong>.</li>
          <li>Select the token you want to receive in <strong className="text-[var(--clr-heading)]">You Get</strong>.</li>
          <li>Enter an amount. The output calculates automatically.</li>
          <li>Click <strong className="text-[var(--clr-heading)]">Swap</strong> and confirm in your wallet.</li>
        </ol>
        <p className="text-xs text-[var(--clr-body)] mt-3 opacity-70">Slippage tolerance can be adjusted via the settings icon. A A &ldquo;no liquidity&rdquo; message means that pair has no pool yet.</p>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-bold text-[var(--clr-heading)] mb-3 border-b border-[var(--clr-border)] pb-2">Adding liquidity</h2>
        <p className="text-sm text-[var(--clr-body)] mb-3">Deposit two tokens into a pool and earn a share of every 0.30% swap fee generated by that pool.</p>
        <ol className="space-y-2 text-sm text-[var(--clr-body)] list-decimal list-inside">
          <li>Go to <strong className="text-[var(--clr-heading)]">Pools</strong> → <strong className="text-[var(--clr-heading)]">Add V2 Liquidity</strong>.</li>
          <li>Select both tokens. Enter an amount for one — the other calculates from the pool ratio.</li>
          <li>Click <strong className="text-[var(--clr-heading)]">Supply</strong> and confirm both transactions (approve + deposit).</li>
          <li>Your LP tokens appear under <strong className="text-[var(--clr-heading)]">Your V2 Liquidity</strong>.</li>
        </ol>
        <div className="mt-4 p-3 rounded-lg bg-[rgba(227,179,65,0.08)] border border-[rgba(227,179,65,0.2)] text-xs text-[var(--clr-body)]">
          <strong className="text-[var(--ae-aurum)]">Impermanent loss:</strong> If the price ratio between your two tokens changes significantly while you are an LP, you may receive back less value than deposited. Swap fees earned offset this risk.
        </div>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-bold text-[var(--clr-heading)] mb-3 border-b border-[var(--clr-border)] pb-2">Removing liquidity</h2>
        <ol className="space-y-2 text-sm text-[var(--clr-body)] list-decimal list-inside">
          <li>Go to <strong className="text-[var(--clr-heading)]">Pools</strong> → <strong className="text-[var(--clr-heading)]">Your V2 Liquidity</strong>.</li>
          <li>Select the pool and click <strong className="text-[var(--clr-heading)]">Remove</strong>.</li>
          <li>Choose how much to withdraw and confirm the transaction.</li>
        </ol>
      </section>

      <section className="mb-10">
        <h2 className="text-lg font-bold text-[var(--clr-heading)] mb-3 border-b border-[var(--clr-border)] pb-2">Safety</h2>
        <ul className="space-y-2 text-sm text-[var(--clr-body)] list-disc list-inside">
          <li>Filament will never ask for your seed phrase or private key.</li>
          <li>Always verify you are on <strong className="text-[var(--clr-heading)]">filament.exchange</strong>.</li>
          <li>Check token contract addresses on lightscan.app before trading unknown tokens.</li>
          <li>Transactions cannot be reversed — confirm carefully before signing.</li>
        </ul>
      </section>

      <section>
        <h2 className="text-lg font-bold text-[var(--clr-heading)] mb-3 border-b border-[var(--clr-border)] pb-2">Contracts</h2>
        <div className="rounded-xl bg-[var(--ae-haze)] border border-[var(--clr-border)] p-4 text-sm font-mono text-[var(--clr-body)] space-y-1">
          <div><span className="text-[var(--ae-aurum)]">WLCAI</span> — 0xD73cedfc5b894323BdB18A1e31E7BB186fCe5F64</div>
          <div><span className="text-[var(--ae-aurum)]">Factory</span> — 0x5Cf3b069dDB232d1adc5139a9eFb30C48F629389</div>
          <div><span className="text-[var(--ae-aurum)]">Router</span> — 0x0fA126B579eA894baD98D89815B3494640d29ac6</div>
        </div>
      </section>
    </div>
  );
}
